CREATE DATABASE ONLINE_LEARNING_SYSTEM;
USE ONLINE_LEARNING_SYSTEM;

-- bang student
CREATE TABLE STUDENT (
    STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_FULLNAME VARCHAR(100) NOT NULL,
    STUDENT_DATEBIRTH DATE,
    STUDENT_EMAIL VARCHAR(255) UNIQUE
);

-- bang teacher
CREATE TABLE TEACHER (
    TEACHER_ID INT AUTO_INCREMENT PRIMARY KEY,
    TEACHER_FULLNAME VARCHAR(100) NOT NULL,
    TEACHER_EMAIL VARCHAR(255) UNIQUE
);

-- bang khoa hoc
CREATE TABLE COURSE (
    COURSE_ID INT AUTO_INCREMENT PRIMARY KEY,
    COURSENAME VARCHAR(150) NOT NULL,
    COURSE_DESCRIPTION TEXT,
    NUMBER_OF_SESSIONS INT CHECK (NUMBER_OF_SESSIONS > 0),
    TEACHER_ID INT NOT NULL,
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER(TEACHER_ID)
);

-- bang dang ky
CREATE TABLE ENROLLMENT (
    STUDENT_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    ENROLL_DATE DATE DEFAULT  CURRENT_TIMESTAMP,
    PRIMARY KEY (STUDENT_ID, COURSE_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

-- bang ket qua
CREATE TABLE SCORE (
    STUDENT_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    MIDSCORE DECIMAL(4,2) CHECK(MIDSCORE >= 0 AND MIDSCORE <= 10),
    ENDSCORE DECIMAL(4,2) CHECK(ENDSCORE >= 0 AND ENDSCORE <= 10),
    PRIMARY KEY (STUDENT_ID, COURSE_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

-- add sv
INSERT INTO STUDENT(STUDENT_FULLNAME, STUDENT_DATEBIRTH, STUDENT_EMAIL)
VALUES
('TRAN MINH QUANG', '2002-03-01', 'quang@gmail.com'),
('LE THI HOA', '2001-06-12', 'hoa@gmail.com'),
('PHAM VAN NAM', '2000-09-21', 'nam@gmail.com'),
('DO THI LAN', '2003-11-05', 'lan@gmail.com'),
('HOANG ANH TUAN', '2002-07-17', 'tuan@gmail.com');

-- add gv
INSERT INTO TEACHER (TEACHER_FULLNAME, TEACHER_EMAIL)
VALUES
('NGUYEN VAN BINH', 'binh@gmail.com'),
('TRAN THI HANG', 'hang@gmail.com'),
('LE VAN SON', 'son@gmail.com'),
('PHAM THI DAO', 'dao@gmail.com'),
('HOANG VAN DUC', 'duc@gmail.com');

-- add khóa hoc
INSERT INTO COURSE (COURSENAME, COURSE_DESCRIPTION, NUMBER_OF_SESSIONS, TEACHER_ID)
VALUES
('MYSQL CO BAN', 'HOC CO BAN VE MYSQL', 20, 1),
('JAVASCRIPT CO BAN', 'LAP TRINH JS TU CO BAN', 22, 2),
('PYTHON FOUNDATION', 'NHAP MON PYTHON', 18, 3),
('JAVA CORE PROGRAMMING', 'LAP TRINH JAVA', 24, 4),
('REACTJS FRONTEND', 'XAY DUNG WEB VOI REACT', 18, 5);

-- dang ky
INSERT INTO ENROLLMENT (STUDENT_ID, COURSE_ID)
VALUES
(1,2),
(2,3),
(3,4),
(4,5),
(5,1);

-- diem
INSERT INTO SCORE (STUDENT_ID, COURSE_ID, MIDSCORE, ENDSCORE)
VALUES
(1,2,7.5,8.0),
(2,3,9.0,9.5),
(3,4,6.0,7.0),
(4,5,8.5,8.75),
(5,1,5.5,6.25);

-- cap nhat
UPDATE STUDENT
SET STUDENT_EMAIL = 'updated@gmail.com'
WHERE STUDENT_ID = 3;

UPDATE COURSE
SET COURSE_DESCRIPTION = 'KHOA HOC CAP NHAT'
WHERE COURSE_ID = 5;

UPDATE SCORE
SET ENDSCORE = 10
WHERE STUDENT_ID = 1 AND COURSE_ID = 2;

-- xoa
DELETE FROM ENROLLMENT
WHERE STUDENT_ID = 5 AND COURSE_ID = 1;

DELETE FROM SCORE
WHERE STUDENT_ID = 3 AND COURSE_ID = 4;

-- truy van
SELECT * FROM STUDENT;
SELECT * FROM TEACHER;
SELECT * FROM COURSE;
SELECT * FROM ENROLLMENT;
SELECT * FROM SCORE;